<?php
    $this->headTitle('Edit Page');
    $this->headTitle($page->getTitle());
?>

<h1>Edit Page</h1>

<?php
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);

?>

<div class="form-container container">
    <div class="col-md-12">
<?php

echo $this->formLabel($form->get('urlIdentifier'));
echo $this->formText($form->get('urlIdentifier'));
echo $this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>')
    ->render($form->get('urlIdentifier'));
?>
    </div>
</div>


<div class="form-container container">
    <div class="col-md-12">
<?php

echo $this->formLabel($form->get('title'));
echo $this->formText($form->get('title'));
echo $this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>')
    ->render($form->get('title'));
?>
    </div>
</div>

<div class="form-container container">
    <div class="col-md-12">
<?php
echo $this->formMarkdown($form->get('description'));
echo $this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>')
    ->render($form->get('description'));
?>
    </div>
</div>

<div class="form-container container">
    <div class="col-md-12">
<?php
echo $this->formLabel($form->get('sort'));
echo $this->formText($form->get('sort'));
echo $this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>')
    ->render($form->get('sort'));
?>
    </div>
</div>

<div class="form-container container">
    <div class="col-md-12">
<?php
echo $this->formLabel($form->get('isPublished'));
echo $this->formCheckbox($form->get('isPublished'));
echo $this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>')
    ->render($form->get('isPublished'));
?>
    </div>
</div>

<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>
