<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
            echo $this->headTitle()->prepend($this->translate('sfphp.org'))
                ->setSeparator(' - ')
                ->setAutoEscape(false)
                ;
        ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet($this->basePath() . '/bower_components/bootstrap/dist/css/bootstrap.min.css')
            ->appendStylesheet($this->basePath() . '/bower_components/bootstrap/dist/css/bootstrap-theme.min.css')
            ->appendStylesheet($this->basePath() . '/bower_components/angular-busy/dist/angular-busy.css')
            ->appendStylesheet($this->basePath() . '/bower_components/angular-loading-bar/build/loading-bar.css')
            ->appendStylesheet($this->basePath() . '/bower_components/angular-bootstrap-lightbox/dist/angular-bootstrap-lightbox.css')
            ->appendStylesheet($this->basePath() . '/bower_components/font-awesome/css/font-awesome.min.css')
            ->appendStylesheet($this->basePath() . '/css/style.css')
            ;
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js')
            ->appendFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
            ->appendFile($this->basePath() . "/bower_components/angular/angular.min.js")
            ->appendFile($this->basePath() . '/bower_components/angular-touch/angular-touch.min.js')
            ->appendFile($this->basePath() . '/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js')
            ->appendFile($this->basePath() . '/bower_components/angular-loading-bar/build/loading-bar.min.js')
            ->appendFile($this->basePath() . '/bower_components/angular-bootstrap-lightbox/dist/angular-bootstrap-lightbox.min.js')
            ->appendFile($this->basePath() . '/bower_components/angular-filter/dist/angular-filter.min.js')
            ->appendFile($this->basePath() . '/bower_components/angular-busy/dist/angular-busy.min.js')
            ->appendFile($this->basePath() . '/bower_components/angular-sanitize/angular-sanitize.min.js')
            ->appendFile($this->basePath() . '/bower_components/angular-encode-uri/dist/angular-encode-uri.min.js')
            ->appendFile($this->basePath() . '/bower_components/markdown/lib/markdown.js')
            ;

        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav dropdown-menu-right pull-right">
                        <?php
                        if ($this->identity()) {
                        ?>
                        <li id="user-menu" class="dropdown">
                            <a id="user-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                <?= $this->escapeHtml($this->identity()->getName()); ?>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="user-drop" role="menu">
                                <li role="menuitem"><a href="<?= $this->url('member'); ?>">Profile</a></li>
                                <li role="menuitem"><a href="<?= $this->url('authentication/logout'); ?>">Logout</a></li>
                            </ul>
                        </li>
                        <?php
                        } else {
                        ?>
                            <li><a href="<?= $this->url('authentication') ?>">Login</a></li>
                        <?php
                        }
                        ?>
                    </ul>

                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    <?php
                    // Fetch all published pages
                    foreach ($this->getPages(null, true) as $page) {
                    ?>
                        <li><a href="<?= $this->url('page', ['url-identifier' => $page->getUrlIdentifier()]) ?>"><?= $this->escapeHtml($page->getTitle()); ?></a></li>
                    <?php
                    }
                    ?>

                    <?php
                    if ($this->isAllowed('administration', 'access')) {
                    ?>
                        <li><a href="<?= $this->url('admin') ?>">Administration</a></li>
                    <?php
                    }
                    ?>

                    </ul>

                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
